<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V0E91U8" failures="1" tests="5" name="Test" time="20.039" errors="0" timestamp="2022-05-31T15:21:04 IST">
  <testcase classname="Com.SaouceDemo.TestClass.TC04_ProceedToCheckOut" name="PersonalInfoAdd" time="0.471"/>
  <testcase classname="Com.SaouceDemo.TestClass.TC01_LoginPage_FunctionalityCheck" name="loginFunctinality" time="0.008"/>
  <testcase classname="Com.SaouceDemo.TestClass.TC03_ProductAddToCart" name="productaddToCart" time="0.266">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [6] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [6] but found [https://www.saucedemo.com/inventory.html]
at Com.SaouceDemo.TestClass.TC03_ProductAddToCart.productaddToCart(TC03_ProductAddToCart.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- productaddToCart -->
  <testcase classname="Com.SaouceDemo.TestClass.TC005_addPersonalInfo" name="personalInfoAdd" time="0.538"/>
  <testcase classname="Com.SaouceDemo.TestClass.TC02_logoutfunc" name="logoutFuncatinality" time="0.18"/>
</testsuite> <!-- Test -->
